project:
  type: website
  output-dir: docs

website:
  title: "finalproject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Coursework.qmd

format:
  html:
    theme:
      - Litera
      - brand
    css: styles.css
    toc: true

editor: visual

